name: Deploy Client to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Server Dependencies
        run: npm install

      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        env:
          REACT_APP_API_ROOT: https://spotify-lyrics-viewer.onrender.com
          REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID: G-GHCZ0LMQWH
          REACT_APP_TRACK_CHECK_DELAY_SECONDS: 5
          CI: false
        working-directory: ./client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: gh-pages
          cname: spotify-lyrics-viewer.nitratine.net
          force_orphan: true # Only keep latest commit in gh-pages (to keep repo size down)
